### ISSUE TITLE
[amcl v3.1 go] Pair.Ate no longer calls affine() on input and gives different results than amcl v2 

### ISSUE THREAD

**Issue by manudrijvers** [milagro-crypto/amcl#17]
I'm using the go version of amcl and recently switched from v2 to v3 and I observed some different behavior: I have ECP p1, p2, and ECP2 q1, q2 and I know that the pairing of p1 and q1 should be equal to the pairing of p2 and q2 and this was true in amcl v2. With v3, the results are not equal and I noticed that ate() in v3 no longer calls affine() on its inputs. After calling affine() on the input points first, the pairing gives the expected results. It seems to me that the pairing isn't a valid pairing unless the input is in affine form, or am I missing something?

**Comment by kealan** [comment]
Hi Yes, that is true. 
In the function Ate these lines are commented out;
	//P.affine()
	//Q.affine()
So these P and Q inputs must be converted to affine before this function is used.

**Comment by manudrijvers** [comment]
Thanks for your reply kealan. The function affine() is private and is therefore not available to users of the library, so I think it would make sense to expose this function. There are many more private methods that I think users would need, which is why I exposed many methods in [my fork](https://github.com/manudrijvers/amcl/tree/master/go) in the *-additions.go files, perhaps you could consider exposing some of those functions as well.

**Comment by manudrijvers** [comment]
I see you made Affine public, thanks!
