### ISSUE TITLE
Publish artifacts in the central maven repository

### ISSUE THREAD

**Issue by manudrijvers** [milagro-crypto/amcl#18]
Hi amcl team,

I'm a happy user of your library, thanks for making this available as open source software. I'm building java software on top of amcl and want to release this as open source software, but the amcl dependency is a bit difficult. I don't want to include amcl in my repository, and I don't want to require my users to fetch the amcl source code and run the configuration script either. Resolving the amcl dependency could be greatly simplified by publishing the java amcl artifacts in the maven central repository. Would you consider doing so? 

Thanks,
Manu

**Comment by mcarrickscott** [comment]
Hello Manu,

We have no experience of using maven, but at the same time we have no major
objection. Other than that we are adverse to having another layer of
maintenance.

Its just for Java, right?

Perhaps you might educate us a little as to what is involved?

Mike

**Comment by manudrijvers** [comment]
Hi Mike,

Thanks for your quick response, and I'm happy to hear you're open to the idea! Correct, this is only about the java version, although I would have similar questions about making the go code more easily usable for open source software, but let's take it one step at a time. 

To turn this into a maven project, you first need a pom.xml that as a minimum defines your 'group id' (for you I guess that would be org.apache.milagro, see more info [here](http://central.sonatype.org/pages/choosing-your-coordinates.html)) and an artifact id, that would be amcl. Furthermore, your package should start with your groupid, so you would need to change the package to org.apache.milagro.amcl. Your project needs to be structured in [the way that maven expects it to](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html). Finally, you may want to maintain a repository that contains the configured files, i.e., on which the config.py script has already been executed. I actually already did all these steps while working on my own software, so you can see an example in [my fork](https://github.com/manudrijvers/amcl/tree/master/java), except that I used a different group id. I think the simplest solution for you would be to have a separate repo similar to my fork, that can (automatically) be updated from the working repository using a modified config script.

When you have a repository containing the code as a maven project, you follow [these ](http://central.sonatype.org/pages/ossrh-guide.html) steps. Then, when others want to use your library in another maven project, they can simply put 
```
<dependency>
    <groupId>com.apache.milagro</groupId>
    <artifactId>amcl</artifactId>
    <version>3.1</version>
</dependency>
```
in their pom.xml, and maven will find the binary from maven central automatically (for e.g. gradle projects, something similar can be done). Feel free to write me at 'mdr at zurich ibm com' and let me know if I can help in any way!

**Comment by mcarrickscott** [comment]
Hmm. Seems like a bit of a learning curve!

From a quick look at your fork it would appear that when you run config.py,
you create a library that supports all of the curves, and only for the
64-bit version.

We would like to keep it so that the user still gets to select 32 or 64-bit
and only for the curves they need. Obviously we want to keep it as general
purpose as possible.

Maybe what we need is another set of config.py files that automatically
generates a pom.xml file, and creates an output repository that uses the
maven directory structure. Then leave it to the user to follow the final
steps to install it in the central repository for their own use.

What do you think?


Mike

**Comment by manudrijvers** [comment]
I see your point regarding the 32 and 64 bit and the curves chosen. On the other hand, I think the purpose of distributing something in the maven central repository is that users of open source software that uses amcl don't have to do anything to get amcl. It is not feasible to publish every possible configuration of amcl on maven central, so then if we go down this route, we have to make some choices. Perhaps a compromise would be to make two or those configured projects, one for 32 bit and one for 64 bit, while still containing all possible curves, and publish these two versions with artifactids amcl32 and amcl64 to maven central. This compromise does make the jars a bit larger, but brings the simplicity that everybody can simply compile without needing to first fetch, configure, and compile amcl. And if somebody really need a small jar then they can simply use the current approach and manually configure amcl. How would you feel about this approach?

**Comment by mcarrickscott** [comment]
I suggest a two stage approach. First we will produce config files to
output a file structure and pom.xml file which is maven compatible. We will
learn a lot about maven just by doing that.

Then we can see if we want to take it further ourselves, or just let third
parties fork it from there.


Mike

**Comment by manudrijvers** [comment]
That makes sense, thanks a lot for looking into this. Could you perhaps give some rough estimates on the timeline of these steps, and by when you could take a decision on whether you proceed to upload artifacts to maven central? I am somewhat blocked by this, so for my planning it'd be great to know what to expect.

**Comment by mcarrickscott** [comment]
Am working on it, will get back.

Should have something  by next week...

Mike

**Comment by manudrijvers** [comment]
Fantastic, thanks again!

**Comment by mcarrickscott** [comment]
Hello Manu,


Phase 1 completed. I have radically changed the file structure for the Java
version to make a better fit with maven. I want to pause here for a couple
of days to see if anyone screams(!)

Can you have a look and check it out. Then maybe indicate again the next
steps required to get it from here up onto a central repository. Keeping it
all as simple as possible.

I am under advice not to increase the number of platforms we need to
maintain.


Mike

**Comment by manudrijvers** [comment]
Thanks for putting it on maven!

https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.miracl.milagro.amcl%22
