### ISSUE TITLE
Expose functions in go

### ISSUE THREAD

**Issue by manudrijvers** [milagro-crypto/amcl#19]
Hi amcl team,

I noticed that many functions that any user of amcl would need (e.g., `ECP.add`) are not exposed in go (i.e., have a name starting with lowercase). In the java version of the library, these methods are public. I think it would make sense to expose the same methods across the languages, and I'd particularly be happy if the following methods could be exposed in go (note that this list is incomplete, there are probably many more functions exposed in java and not exposed in go that I don't list here, these are just the ones I need):

- `BIG.mod`
- `BIG.fromBytes`
- `BIG.modmul`
- `BIG.toBytes`
- `BIG.invmodp`
- `BIG.equals`
- `BIG.modneg`
- `ECP.toBytes`
- `ECP.mul2`
- `ECP.getX`
- `ECP.getY`
- `ECP.add`
- `ECP.equals`
- `ECP.sub`
- `ECP2.toBytes`
- `ECP2.add`
- `ECP2.getX`
- `ECP2.getY`
- `ECP2.mul`
- `ECP2.equals`
- `ECP2.sub`
- `FP12.inverse`
- `FP12.mul`
- `FP12.toBytes`
- `FP12.pow`

Thanks!

**Comment by mcarrickscott** [comment]
Hello Manu,

Yes, you are right more of those functions should be made public.

So we made a start with your list....

We just need to be careful not to upset our own APIs...

Mike

**Comment by manudrijvers** [comment]
Thanks so much Mike! I missed three in my first list: `FP2.getA`, `FP2.getB`, `BIG.plus`, could these also be made public? I'm happy to make a PR if you want.

**Comment by mcarrickscott** [comment]
Hi Manu,

Done!

Mike

**Comment by manudrijvers** [comment]
Fantastic, thanks again!
