### ISSUE TITLE
Add BLS12-381 curve

### ISSUE THREAD

**Issue by Scratch-net** [milagro-crypto/amcl#29]
Could you please add this new zk-snarks curve?
https://blog.z.cash/new-snark-curve/

**Comment by mcarrickscott** [comment]
OK, will do.

I did some initial checks, and its fully compatible.

One minor niggle - the equation y^2=x^3-11 would be a better curve, as it
has the nice nothing-up-my-sleeve generator point (3,4)


Mike

**Comment by mratsim** [comment]
This seems to have been implemented in https://github.com/milagro-crypto/amcl/commit/9f1c97b1ec60d57906ed62bf109d8e87cc9ba33b. Is there anything missing?

**Comment by mcarrickscott** [comment]
Don't think so..

Mike

**Comment by Scratch-net** [comment]
Thanks, will check
