### ISSUE TITLE
[Rust] Mismatched types 

### ISSUE THREAD

**Issue by rafaeltm** [milagro-crypto/amcl#34]
Hi,
In version3, when you try to compile the Rust code  with nist521 curve support:

src\nist521\rom.rs
mismatched types
   = note: expected type `[i64; 7]`
                found type `[i64; 9]`

**Comment by mcarrickscott** [comment]
Typo in rom file rom_nist521_64.rs

use nist384::big::NLEN;

should be

use nist521::big::NLEN;

Mike
