### ISSUE TITLE
Point Compression

### ISSUE THREAD

**Issue by manudrijvers** [milagro-crypto/amcl#36]
Are there any plans on adding point compression for ECP.toBytes and ECP2.toBytes? In blockchain applications, the size of objects is often very important as it will be sent to many nodes and stored for a long time, so built-in functions supporting serialization with point compression would be very helpful.

**Comment by mcarrickscott** [comment]
Yes, probably a good idea now that compression patents are finally dead.

I would propose to follow http://www.secg.org/sec1-v2.pdf section 2.3.3

ECP.toBytes will need a new parameter to indicate whether or not
compression is desired. ECP.fromBytes will dedetermine from the first octet
whether or not compression has been used, and act accordingly.


Mike

**Comment by manudrijvers** [comment]
Thanks for your prompt reply Mike! Yes, that sounds perfect.

**Comment by manudrijvers** [comment]
I see that [you added it](https://github.com/milagro-crypto/amcl/commit/ac5884aec7383aa974628892728b9abb264a8f77), thanks a lot!
