### ISSUE TITLE
Bug with "infinum" point for ECP

### ISSUE THREAD

**Issue by KitHat** [milagro-crypto/amcl#55]
During refactoring and testing the AMCLv3 I met a problem.
I have implemented equals that just compares everything inside of ECP, BIG and so on.
This is a piece of code to reproduce it.
```rust
let mut a = ECP::new();
a.inf();
let big = BIG::frombytes(&[0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,0]);
let mut b = ECP::new_big(&big);
let mut c = ECP::new_big(&big);
b.add(a);
assert_eq!(b, c);
```
In short, when we add a neutral element (so called "infinum") to any other point on curve, we should receive the same element. But now we don't receive it.

**Comment by mcarrickscott** [comment]
Hmm. Which curve?

Mike

**Comment by KitHat** [comment]
Looks like all of them, but I have tested on bn254

**Comment by mcarrickscott** [comment]
OK, thanks. How is assert_eq implemented?

Two points can be numerically different while being mathematically
identical.

Mike

**Comment by KitHat** [comment]
It just checks them numerically.
What is the correct rule for equality then?

**Comment by KitHat** [comment]
Oh, I see. Now it works. I will now redefine some traits and it will use your method.
Thank you!
