### ISSUE TITLE
Multiplication with negative number (BIG) seems incorrect

### ISSUE THREAD

**Issue by lovesh** [milagro-crypto/amcl#67]
I want to be able to multiply to numbers modulo the curve order, i am using the function `modmul` from `big.rs`. Here is some sample code where i try to multiply `1` with `-1`  modulo curve order, the result should be `-1` but its not. I have added the display trait to `BIG` to print each `Chunk` followed by an space, in a single line.

``` 
impl fmt::Display for BIG {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        for i in 0..NLEN-1 {
            write!(f, "{} ", self.w[i]);
        }
        write!(f, "{}", self.w[NLEN-1])
    }
}
```

Test code

```
let CurveOrder = BIG::new_ints(&rom::CURVE_ORDER);
let mut one = BIG::new_int(1);
let mut neg_one = BIG::new_int(-1);
neg_one.rmod(&CurveOrder);
println!("-1 is: {}", &neg_one);
// the ouput is 288230376151711743 288230376151711743 288230376151711743 288230376151711743 288230376151711743 288230376151711743 -1
let mut pr = BIG::modmul(&one, &neg_one, &CurveOrder);
println!("product of 1 and -1 modulo curve order is {}", &pr);
// the ouput is 288230376151711743 288230376151711743 288230376151711743 288230376151711743 288230376151711743 288230376151711743 288230376151711743
```

Both `pr` and `neg_one` should be same as they have been reduced modulo the curve order but they are not.
Secondly i don't understand why `neg_one` is represented the way it is, it should be `-1 0 0 0 0 0 0` which happens if i omit the step `neg_one.rmod(&CurveOrder);`.  It looks like every chunk except first is turned to 2^BASEBITS - 1 and the number is reversed.

**Comment by mcarrickscott** [comment]
Hello Lovesh,

As it says in the manual "AMCL has no support for negative numbers". This
may seem surprising, but in the world of numbers modulo a prime q, there
are no negative numbers, just positive numbers in the range 0 to q-1

The function modmul() performs modular multiplication, modulo the curve
order q.

So the correct representation of -1, is actually the positive number q-1.


Mike

**Comment by lovesh** [comment]
Thanks Mike for replying.

Does it mean that if 2 numbers, say `z` and `o` as 0 and 1 respectively and i do call `BIG::sub` with `z` and `o`, the result cannot be further used? 

Test code
```
let mut zero = BIG::new_int(0);
zero.sub(&one);
zero.rmod(&CurveOrder);
println!("subtraction of 0 and 1 is {}", &zero);
// output is 288230376151711743 288230376151711743 288230376151711743 288230376151711743 288230376151711743 288230376151711743 -1
let mut pr = BIG::modmul(&one, &zero, &CurveOrder);
println!("product of 1 and -1 modulo curve order is {}", &pr);
// output is 288230376151711743 288230376151711743 288230376151711743 288230376151711743 288230376151711743 288230376151711743 288230376151711743
```
The value of -1 is different in both cases above.

Secondly -1 (either value from above) does not equal `CurveOrder` - 1 as the test below shows
```
let mut co = CurveOrder.clone();
co.sub(&one);
co.rmod(&CurveOrder);
println!("subtraction of curve order and 1 is {}", &co);
// the output is 288230371856744448 245728479295242175 108227790465160507 93632717821889767 7597479 0 0
```

**Comment by mcarrickscott** [comment]
Yes, subtracting a bigger number from a smaller number (as in  zero.sub(&one);)
results in an error, and should never happen. There is no valid
representation for -1.

Given a,b < q then

a-b mod q =a+q-b mod q

Mike

**Comment by lovesh** [comment]
Seems like using `modneg` is the right thing to do. Like this
```
let mut zero = BIG::new_int(0);
let neg = BIG::modneg(&one, &CurveOrder);
println!("Negative 1 is {}", &neg);
zero.add(&neg);
println!("subtraction of 0 and 1 is {}", &zero);
let mut pr = BIG::modmul(&one, &zero, &CurveOrder);
println!("product of 1 and -1 modulo curve order is {}", &pr);
```

**Comment by lovesh** [comment]
Thanks Mike for your help.
